#!/bin/bash
##############################################################################
# PHASE_2.1_pipeline_setup/submit_prepared.sh
#
# Purpose:
#   Convert cactus-prepare output into SLURM job submissions for Grace.
#
#   cactus-prepare decomposes a large alignment into a series of steps:
#     1. cactus-blast (pairwise alignment per subtree)
#     2. cactus-align (progressive alignment per subtree)
#     3. cactus-hal-append (merge subtree HALs)
#
#   This script wraps each step in a SLURM sbatch call with appropriate
#   resources and dependency chains.
#
# Prerequisites:
#   - setup_grace.sh has been run
#   - prepared/steps.sh exists (generated by cactus-prepare)
#   - Test alignment passed (test_alignment.slurm)
#
# Usage:
#   bash submit_prepared.sh [--dry-run]
#
# Options:
#   --dry-run   Print SLURM submission commands without actually submitting
##############################################################################

set -euo pipefail

# ============================================================================
# CONFIGURATION
# ============================================================================

NETID="${USER}"
PROJECT_DIR="/scratch/user/${NETID}/scarab"
CONTAINER="${PROJECT_DIR}/cactus_v2.9.3.sif"
PREPARED_DIR="${PROJECT_DIR}/prepared"
STEPS_FILE="${PREPARED_DIR}/steps.sh"
SLURM_DIR="${PROJECT_DIR}/slurm_scripts"
LOG_DIR="${PROJECT_DIR}/logs/alignment"

SING_PREFIX="singularity exec --cleanenv \
  -B ${PROJECT_DIR}:${PROJECT_DIR} \
  -B /tmp:/tmp \
  ${CONTAINER}"

# SLURM defaults for Cactus steps
# Blast steps are I/O heavy; align steps are CPU heavy
BLAST_PARTITION="long"
BLAST_TIME="2-00:00:00"
BLAST_CPUS=48
BLAST_MEM="384G"

ALIGN_PARTITION="long"
ALIGN_TIME="3-00:00:00"
ALIGN_CPUS=48
ALIGN_MEM="384G"

APPEND_PARTITION="short"
APPEND_TIME="04:00:00"
APPEND_CPUS=16
APPEND_MEM="128G"

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
    DRY_RUN=true
    echo "=== DRY RUN MODE — no jobs will be submitted ==="
    echo ""
fi

# ============================================================================
# VALIDATION
# ============================================================================

echo "SCARAB — Submit Prepared Alignment Steps"
echo "========================================="
echo ""

if [ ! -f "${STEPS_FILE}" ]; then
    echo "ERROR: ${STEPS_FILE} not found."
    echo "Run setup_grace.sh first to generate cactus-prepare output."
    exit 1
fi

if [ ! -f "${CONTAINER}" ]; then
    echo "ERROR: Cactus container not found: ${CONTAINER}"
    exit 1
fi

mkdir -p "${SLURM_DIR}" "${LOG_DIR}"

# ============================================================================
# PARSE CACTUS-PREPARE STEPS
# ============================================================================

echo "Parsing cactus-prepare steps from: ${STEPS_FILE}"
echo ""

# Count step types
BLAST_COUNT=$(grep -c "^cactus-blast\|cactus-blast " "${STEPS_FILE}" 2>/dev/null || echo 0)
ALIGN_COUNT=$(grep -c "^cactus-align\|cactus-align " "${STEPS_FILE}" 2>/dev/null || echo 0)
APPEND_COUNT=$(grep -c "^hal_\|halAppendSubtree\|cactus-hal-append" "${STEPS_FILE}" 2>/dev/null || echo 0)
TOTAL_STEPS=$(grep -c "^[a-z]" "${STEPS_FILE}" 2>/dev/null || echo 0)

echo "  Total steps:    ${TOTAL_STEPS}"
echo "  Blast steps:    ${BLAST_COUNT}"
echo "  Align steps:    ${ALIGN_COUNT}"
echo "  Append/merge:   ${APPEND_COUNT}"
echo ""

# ============================================================================
# GENERATE SLURM SCRIPTS FOR EACH STEP
# ============================================================================

echo "Generating SLURM scripts..."

STEP_NUM=0
PREV_JOBID=""
DEPENDENCY_FLAG=""

while IFS= read -r line; do
    # Skip empty lines and comments
    [[ -z "${line}" ]] && continue
    [[ "${line}" =~ ^# ]] && continue
    [[ ! "${line}" =~ ^[a-z] ]] && continue

    ((STEP_NUM++))

    # Determine step type and resources
    if echo "${line}" | grep -q "cactus-blast"; then
        STEP_TYPE="blast"
        PARTITION="${BLAST_PARTITION}"
        TIME="${BLAST_TIME}"
        CPUS="${BLAST_CPUS}"
        MEM="${BLAST_MEM}"
    elif echo "${line}" | grep -q "cactus-align"; then
        STEP_TYPE="align"
        PARTITION="${ALIGN_PARTITION}"
        TIME="${ALIGN_TIME}"
        CPUS="${ALIGN_CPUS}"
        MEM="${ALIGN_MEM}"
    else
        STEP_TYPE="merge"
        PARTITION="${APPEND_PARTITION}"
        TIME="${APPEND_TIME}"
        CPUS="${APPEND_CPUS}"
        MEM="${APPEND_MEM}"
    fi

    SCRIPT="${SLURM_DIR}/step_${STEP_NUM}_${STEP_TYPE}.slurm"

    cat > "${SCRIPT}" <<SLURM
#!/bin/bash
#SBATCH --job-name=scarab_${STEP_TYPE}_${STEP_NUM}
#SBATCH --partition=${PARTITION}
#SBATCH --time=${TIME}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${CPUS}
#SBATCH --mem=${MEM}
#SBATCH --output=${LOG_DIR}/step_${STEP_NUM}_${STEP_TYPE}_%j.log
#SBATCH --error=${LOG_DIR}/step_${STEP_NUM}_${STEP_TYPE}_%j.err

set -euo pipefail

echo "============================================================"
echo "SCARAB Step ${STEP_NUM}: ${STEP_TYPE}"
echo "Job ID: \${SLURM_JOB_ID}"
echo "Started: \$(date)"
echo "============================================================"

module load Singularity 2>/dev/null || module load singularity 2>/dev/null || true

# Run the cactus step
${SING_PREFIX} \\
    ${line} \\
    --maxCores ${CPUS} \\
    --maxMemory \$(( ${CPUS} * 8 ))G \\
    --binariesMode local

echo ""
echo "Step ${STEP_NUM} (${STEP_TYPE}) completed: \$(date)"
SLURM

    echo "  Step ${STEP_NUM} (${STEP_TYPE}): ${SCRIPT}"

done < "${STEPS_FILE}"

echo ""
echo "Generated ${STEP_NUM} SLURM scripts in ${SLURM_DIR}/"
echo ""

# ============================================================================
# SUBMIT WITH DEPENDENCIES
# ============================================================================

if [ "${DRY_RUN}" = true ]; then
    echo "=== DRY RUN — would submit ${STEP_NUM} jobs ==="
    echo ""
    echo "To submit for real, run:"
    echo "  bash submit_prepared.sh"
    exit 0
fi

echo "Submitting SLURM jobs with dependency chains..."
echo ""

PREV_JOBID=""
for SCRIPT in $(ls "${SLURM_DIR}"/step_*.slurm | sort -t_ -k2 -n); do
    if [ -n "${PREV_JOBID}" ]; then
        DEPENDENCY_FLAG="--dependency=afterok:${PREV_JOBID}"
    else
        DEPENDENCY_FLAG=""
    fi

    JOBID=$(sbatch ${DEPENDENCY_FLAG} "${SCRIPT}" | awk '{print $NF}')
    STEP_NAME=$(basename "${SCRIPT}" .slurm)
    echo "  ${STEP_NAME}: Job ${JOBID} ${DEPENDENCY_FLAG}"
    PREV_JOBID="${JOBID}"
done

echo ""
echo "All ${STEP_NUM} jobs submitted."
echo "Final job ID: ${PREV_JOBID}"
echo ""
echo "Monitor with:"
echo "  squeue -u ${USER}"
echo "  watch -n 30 'squeue -u ${USER}'"
echo ""
echo "When all jobs complete, the final HAL will be at:"
echo "  ${PROJECT_DIR}/hal_files/scarab.hal"
